# Generated by Django 5.2 on 2025-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.FloatField(default=4.99),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
