# Generated by Django 5.2 on 2025-06-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cart_delivery_charge_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
