# Generated by Django 5.2 on 2025-06-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='cart',
        ),
    ]
