# Generated by Django 5.2 on 2025-06-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_orders_amount_remove_cart_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cart'),
        ),
    ]
