# Generated by Django 5.2 on 2025-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='order_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
